### PR TITLE
Rewriting some of the package internal organisation

### PR DESCRIPTION
**Pull request by Aluriak**
This PR needs discussion about the package in a more global view.
The current organisation of the package is simple, but globally in only one file + one submodule (_ply_).
This PR tries to cut out the big _asp.py_ file and to do more pythonic approach for coding style and definitions.

Note: i did not really give a look to the _ply_ submodule, it is always a magic black box to me.

Goals:
- decoupling main parts
- improve API
- keep backward compatibility (to _[python 2](https://github.com/sthiele/pyasp/pull/12#issuecomment-200871947)_ and _pyasp 1.4.2_)
- improved PEP8 compliance
- improved documentation

TODO:
- [X] rename _src/_ to _pyasp/_ (see a8b207e)
- [X] refactor and standardize constants (especially file paths, see 511299b and _constant.py_)
- [X] expose main API types to package level (see 21a3abd and ___init__.py_ file)
- [X] usage example when package runned (see a9bcc71 and ___main__.py_)
- [ ] test the new _OPTIMIZE_ flag handling (see 2725e3f)
- [ ] provides docstring for proper documentation of modules and functions
- [ ] better handling of the generated _asp_{lex,parse}tab.py_ files (create as tempfile ?)
- [ ] refactor the _asp.py_ classes (especially binaries manipulation)
- [ ] detect and handle unused functions (functions currently put inside the _misc.py_ module ; what next ?)
- [ ] provides makefile recipe for documentation autogeneration (sphinx ?)
- [x] setup.py: refactorization & functions (see fca9e4f)
- [X] setup.py: restore Python 2.7 compatibility (cf [this comment](https://github.com/sthiele/pyasp/pull/12#issuecomment-200871947) and 40896e5)
- [ ] using [requests](http://docs.python-requests.org/en/latest/index.html) instead of urllib for pyasp installing ?

### CODE REVIEW

**Comment by Aluriak** [comment]
This PR also works on the packaging, and particularly on the _setup.py_ part. Download of the various binaries can be extended to the three main platforms (linux, mac, windows) and architecture (32 or 64 bits).

Moreover, the access to the binaries directory should be accessed using the standard [pkg_ressources module](https://pythonhosted.org/setuptools/pkg_resources.html).

This last is already partially implemented in the _constant.py_ module, but the installation itself needs work.

**Comment by Aluriak** [comment]
The compatibility with python 2.7 is currently broken, essentially du to:

```
  Running setup.py install for pyasp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nkEMd8/pyasp/setup.py", line 106, in <module>
    'pyasp.ply'
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
      File "/tmp/pip-build-nkEMd8/pyasp/setup.py", line 79, in run
    self.get_binaries(path)
      File "/tmp/pip-build-nkEMd8/pyasp/setup.py", line 53, in get_binaries
    urllib.request.urlretrieve(CLASP_URL, path + "/clasp")
    AttributeError: 'module' object has no attribute 'request'
```

Fixing this problem require to use this snippet in imports:

```
if sys.version_info >= (3,):
    from urllib import request                                                   
    urlretrieve = request.urlretrieve                                            
else:  # python 2 compatibility
    from urllib import urlretrieve   
```

And then use `urlretrieve` in place of the `urllib.request.urlretrieve` call.
This correction will be applyied in this PR. (commit incoming)

However, there is something else, more evil.
According to [this virtualenv issue](https://github.com/pypa/virtualenv/issues/355), and [this SO question](http://stackoverflow.com/questions/29888373/issues-with-getsitepackages-under-a-virtualenv), and [this issue](), virtualenv have a known bug that touch `site` module and particularly the `getusersitepackages` function.

This function is used for user-wide installation of pyasp, so its impossible in python 2.7.

**Comment by Aluriak** [comment]
`setup.py` file is now rewritten, essentially by cut scripts into functions and apply some DRY.
The main behavior of the installation is not changed, while it seems to be the best solution we have currently. (excluding gringo and clasp compilation and binaries embedding)

Because of the virtualenv limitations, python 2.7 can't be supported if inside a virtualenv.

**Comment by Aluriak** [comment]
After tests, pip correctly install pyasp under OS X. (before that, the binaries was not installed)
The commit fca9e4f brings the patch, probably related to macos specific code.

**Comment by sthiele** [comment]
> [Keeping backwards compatibility to python 2.](https://github.com/sthiele/pyasp/pull/12#issuecomment-200871947)

This has a really low priority for me. Here my reasons.
- It introduces another free variable which must be tested, which consumes a lot of time, which we can invest better in other issues.
- Some issues like the bug in the `getusersitepackages` function make total functional equivalence impossible.
- It often complicates the code.
- Python 3 is the future, we should encourage people to update their installations.

> [rename src/ to pyasp/](https://github.com/sthiele/pyasp/commit/a8b207eca020039d0360a1d767a35037f3b02172)

Can you elaborate on why you think this is useful?

> packaging ... can be extended to the three main platforms (linux, mac, windows) and architecture (32 or 64 bits)

I think the main issue are the gringo/clasp binaries. Maybe you have some ideas how to solve it.
- I've got no good process in place to create all these binaries automatically.
- I have no working windows/mac machine to build test.
- I rely on other people building and testing mac/windows versions.
- The gringo maintainer is reluctant to provide 32bit binaries. (He thinks nobody is using it anymore).
- ATM the binaries are located at http://www.cs.uni-potsdam.de/~sthiele/bioasp/downloads/bin/ Maybe we should put them into the git repository from now?
- I suggest dropping 32bit! Having windows would be cool!

> [the installation itself needs work](https://github.com/sthiele/pyasp/pull/12#issuecomment-200395341)

That's the thing that gives me the most headaches right now. The download of the binaries seems to be broken and I can't figure out why. On some machines the package is installed without error messages but no binaries are downloaded.

**Comment by Aluriak** [comment]
#### [This has a really low priority for me. Here my reasons](https://github.com/sthiele/pyasp/pull/12#issuecomment-203835619)

I agree with most of that. However, allowing the python 2 users to use the package without have to touch to the source code, if it's not too costly, seems to be a good idea.

#### [rename src/ to pyasp/](https://github.com/sthiele/pyasp/commit/a8b207eca020039d0360a1d767a35037f3b02172)

Here is _my_ point of view, get from experience and personal preferences:

Using _src/_:
- explicit directory for the sources
- inside the package, imports are done with `from src import …`

Using _pyasp/_:
- inside the package, imports are done with `from pyasp import …`, avoiding some import error in some (specific) cases.
- if any error is raised by the package while used by another package, the source path contains _pyasp_, not _src_.
- when the package is integrated inside a higher level module, using `from src import …` is less explicit than `from pyasp import …`
- its the most common way to do in Python

There is examples of the two possibility in many packages. Using package name is to me, as you can see, more a preference than a real necessity. (in most of case, at least)

[Requests](https://github.com/kennethreitz/requests), [boltons](https://github.com/mahmoud/boltons), [networkx](https://github.com/networkx/networkx) use the package name.
[Watchdog](https://github.com/gorakhargosh/watchdog/) and [matplotlib](https://github.com/matplotlib/matplotlib) use _src_.

#### packaging extended to the three main platforms (linux, mac, windows) and architecture (32 or 64 bits)

Compilation is always a problem, and compile in cross-plateform is possibly too complex to manage. Binaries at potassco.sourceforge.net could be used instead, despite the protection of sourceforge against automatic binaries retrieving.

For the 32bits, its like the python 2.7 support: we should try to keep the compatibility as long as it is not a pain to do.
If nobody scream about python 2.7 since last version, its probably because no one use it anymore.
Let's do the same for 32 bits architectures ?

Another solution is to embeds the binaries inside the package, but i'm not comfortable with that, because ALL the binaries will be installed. Delete the bad ones instead of download the good ones is the globally the same thing. (except the remote download)
Moreover, the git project will instantly grow… git is not dedicated to binaries, and all versions of binaries will be completely saved.
Currently, gringo + gringo4 + clasp = 18 Mo. With 3 plateforms, the total size taken in the git repo will reach 100Mo after two update of the binaries.

The best (?) solution is to embeds the source file, and create a setuptools extension for compile them at the installation. That can be easy (many tools are dedicated to that).
I have a (theorical) personal project about that: use Cython to interface python directly with the C/C++ API of the clingo shared library. That can be a pain to setup, but once done, the API of pyasp will automatically change with clingo versions.

#### the installation itself needs work

Yes, that's the hard part.
Question is: what do we want ? Easy to install ? Quick reactions to clingo update ?

Personally, _pyasp_ is my favorite way to embed ASP in Python because of the easy installation. The official way to do require a manual compilation of clingo, which is not a trivial task despite the doc and used tools. (scons is in python,…)
If we can automatize clingo compilation, we can fully automatize pyasp setup.

For the silently failing download, i think it can be because of urllib, that seems to don't work in some case. (the first version have known bugs on some OS X versions).

**Comment by Aluriak** [comment]
About windows compatibility: i've test it on windows, and it don't work. I'm working on find the installation paths. Once found, the compatibility will be complete. (i hope so)

**Pull request merged**
